In [3]:
import torch, tiktoken

In [4]:
raw_text = "this is an animal"

In [5]:
tokenizer = tiktoken.get_encoding("gpt2")

In [6]:
enc_text = tokenizer.encode(raw_text)
print(enc_text) 

[5661, 318, 281, 5044]


In [22]:
vocab_size = 4
output_dim = 3
inputs = torch.nn.Embedding(vocab_size, output_dim)
print(inputs.weight)

Parameter containing:
tensor([[ 1.0267, -2.1814, -0.5086],
        [ 1.8118,  1.5974, -0.8672],
        [-1.3830, -0.3423, -0.7494],
        [ 0.5550, -1.1884, -0.9085]], requires_grad=True)


In [23]:
inputs = inputs.weight.data
print(inputs)


tensor([[ 1.0267, -2.1814, -0.5086],
        [ 1.8118,  1.5974, -0.8672],
        [-1.3830, -0.3423, -0.7494],
        [ 0.5550, -1.1884, -0.9085]])


In [10]:
inputs.shape

torch.Size([4, 3])

In [11]:
for row in inputs:
    print(row.tolist())

[0.8249934911727905, 0.20475949347019196, -1.8176409006118774]
[0.2683960497379303, -0.15619559586048126, 0.17950648069381714]
[-0.7374725937843323, 0.5850347876548767, 0.29688188433647156]
[0.3095060884952545, -1.1209542751312256, 0.5972728133201599]


In [24]:
x = torch.Tensor([1.1,2.3])
y = torch.Tensor([3.4,-2.1])

In [ ]:
torch.dot(x,y) # dot = x1 *x2 +y1*y2

tensor(-1.0900)

In [26]:
query = inputs[2]
print(query)


tensor([-1.3830, -0.3423, -0.7494])


In [27]:
for i in range(len(inputs)):
    print(torch.dot(query,inputs[i]))

tensor(-0.2921)
tensor(-2.4026)
tensor(2.5914)
tensor(0.3201)


In [28]:
attention_scores2 = torch.empty(len(inputs))
for i in range(len(inputs)):
    attention_scores2[i] = torch.dot(query,inputs[i])
print(attention_scores2)

tensor([-0.2921, -2.4026,  2.5914,  0.3201])


In [29]:
def softmax(x):
    torch.exp(x)/ torch.exp(x)

In [30]:
torch.softmax(attention_scores2, dim = 0)

tensor([0.0480, 0.0058, 0.8577, 0.0885])

In [31]:
attention_scores2.sum()


tensor(0.2168)

In [32]:
context_vector_2 = torch.zeros (query.shape)
for i in range(len(attention_scores2)):
    context_vector_2 += attention_scores2[i] * inputs[i]
context_vector_2

tensor([-8.0592e+00, -4.4684e+00, -7.6133e-04])

In [34]:
attention_weights = inputs @ inputs.T
attention_weights

tensor([[ 6.0715, -1.1835, -0.2921,  3.6243],
        [-1.1835,  6.5864, -2.4026, -0.1051],
        [-0.2921, -2.4026,  2.5914,  0.3201],
        [ 3.6243, -0.1051,  0.3201,  2.5458]])

In [38]:
attention_weights[0].sum


<function Tensor.sum>

In [40]:
context_vectors = attention_weights @ inputs
context_vectors

tensor([[ 6.5047e+00, -1.9343e+01, -5.1356e+00],
        [ 1.3983e+01,  1.4050e+01, -3.2135e+00],
        [-8.0592e+00, -4.4684e+00, -7.6133e-04],
        [ 4.5008e+00, -1.1209e+01, -4.3050e+00]])