In [1]:
import torch
import torch.nn as nn

In [8]:
outputs = torch.randn(3,6)
outputs

tensor([[-0.8586,  0.0670, -0.3040,  0.4122, -0.7844,  1.0732],
        [-0.0573,  1.3836,  0.4028,  0.0379, -2.8845, -0.7538],
        [-2.0314,  1.9026, -0.4535,  0.9250,  2.4918,  0.8743]])

In [13]:
mean = outputs.mean( dim=-1, keepdim=True )
mean

tensor([[-0.0658],
        [-0.3119],
        [ 0.6181]])

In [14]:
sd = outputs.std( dim=-1, keepdim=True)
sd

tensor([[0.7410],
        [1.4413],
        [1.6425]])

In [15]:
normalized_outputs = (outputs - mean)/sd
normalized_outputs

tensor([[-1.0700,  0.1792, -0.3215,  0.6450, -0.9699,  1.5371],
        [ 0.1766,  1.1764,  0.4959,  0.2427, -1.7850, -0.3066],
        [-1.6131,  0.7821, -0.6525,  0.1868,  1.1408,  0.1559]])

In [20]:
normalized_outputs.mean( dim=-1, keepdim=True)

tensor([[     0.0000],
        [    -0.0000],
        [     0.0000]])

In [21]:
normalized_outputs.std( dim=-1, keepdim=True)

tensor([[1.0000],
        [1.0000],
        [1.0000]])

In [19]:
torch.set_printoptions( sci_mode=False )

In [23]:
class LayerNorm(nn.Module):
    def __init__(self, emb_dim):
        super().__init__()
        self.eps = 1e-5
        self.scale = nn.Parameter(torch.ones(emb_dim))
        self.shift = nn.Parameter(torch.zeros(emb_dim))

    def forward(self, x):
        mean = x.mean(dim=-1, keepdim=True)
        var = x.var(dim=-1, keepdim=True, unbiased=False)
        norm_x = (x - mean) / torch.sqrt(var + self.eps)
        return self.scale * norm_x + self.shift
